### ISSUE TITLE
What exactly is this?

### ISSUE THREAD

**Issue by GtaMasterYT** [tchristofferson/PagedInventories#1]
I saw the spigot thread, but I am confused. Does this **make** inventories, or does it **manage** inventories?

**Comment by tchristofferson** [comment]
It manages inventories take a look at [PagedInventory.java](https://github.com/tchristofferson/PagedInventories/blob/master/src/main/java/com/tchristofferson/pagedinventories/PagedInventory.java) to see how.

**Comment by GtaMasterYT** [comment]
Can we get a sample?

**Comment by tchristofferson** [comment]
I added more samples on how to create a paged inventory and how to add pages, check the [readme](https://github.com/tchristofferson/PagedInventories#how-to-use).
